### ISSUE TITLE
dod_certs_to_mobileconfig NoneType error

### ISSUE THREAD

**Issue by pittjl** [brodjieski/macos#1]
I know this was last updated a few years ago, but I tried it out today and got an error. This is using python 3.11. I am able to curl the zip file without issue.

 dod_certs_mobileconfig % python3 dod_certs_to_mobileconfig.py 
Attempting to get .zip file from https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/unclass-certificates_pkcs7_DoD.zip
Traceback (most recent call last):
  File "/Users/jlp/code/dodcerts/macos/dod_certs_mobileconfig/dod_certs_to_mobileconfig.py", line 254, in <module>
    main()
  File "/Users/jlp/code/dodcerts/macos/dod_certs_mobileconfig/dod_certs_to_mobileconfig.py", line 210, in main
    pem_bundle_file, pem_title = find_p7b_file(tempdir)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

**Comment by brodjieski** [comment]
@pittjl Give it a try now. Had to make some adjustments for it to work with latest DOD bundle.

**Comment by pittjl** [comment]
Now a NoneType error in a different location. 

Attempting to get .zip file from https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/unclass-certificates_pkcs7_DoD.zip
Traceback (most recent call last):
  File "/Users/jlp/code/dodcerts/macos/dod_certs_mobileconfig/./dod_certs_to_mobileconfig.py", line 254, in <module>
    main()
  File "/Users/jlp/code/dodcerts/macos/dod_certs_mobileconfig/./dod_certs_to_mobileconfig.py", line 246, in main
    newPayload.addPayloadFromPEM(certData)
  File "/Users/jlp/code/dodcerts/macos/dod_certs_mobileconfig/./dod_certs_to_mobileconfig.py", line 108, in addPayloadFromPEM
    name = name_regex.search(pemfile).group(2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by brodjieski** [comment]
I believe this issue has been resolved... ran the script today and it generated profile.
